# Generated by Django 4.1 on 2022-08-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_path', models.ImageField(blank=True, upload_to='Product_Images')),
                ('status_bit', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('modify_status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cms',
                'verbose_name_plural': 'Cms',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_key', models.CharField(max_length=45)),
                ('conf_value', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('modify_status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=45)),
                ('message', models.TextField()),
                ('note_admin', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=45)),
                ('percent', models.FloatField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('no_of_uses', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coupons',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emails',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PaymentGateway',
                'verbose_name_plural': 'PaymentGateway',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ProductAttributes',
                'verbose_name_plural': 'ProductAttributes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('from_special_price', models.DateField()),
                ('to_special_price', models.DateField()),
                ('quantity', models.IntegerField()),
                ('meta_title', models.CharField(max_length=45)),
                ('meta_desc', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('modify_status', models.BooleanField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=45)),
                ('Lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
                ('status', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(choices=[('M', 'Manager'), ('C', 'Customer'), ('A', 'Admin')], max_length=2)),
                ('fb_token', models.CharField(max_length=100)),
                ('twitter_token', models.CharField(max_length=100)),
                ('google_token', models.CharField(max_length=100)),
                ('registration_method', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.user')),
            ],
            options={
                'verbose_name': 'UserWishList',
                'verbose_name_plural': 'UserWishList',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.user')),
            ],
            options={
                'verbose_name': 'UserAddress',
                'verbose_name_plural': 'UserAddress',
            },
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_names', models.CharField(max_length=45)),
                ('modify_status', models.BooleanField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.products')),
            ],
            options={
                'verbose_name': 'ProductsImages',
                'verbose_name_plural': 'ProductsImages',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.products')),
            ],
            options={
                'verbose_name': 'ProductsCategory',
                'verbose_name_plural': 'ProductsCategory',
            },
        ),
        migrations.CreateModel(
            name='ProductsAttributesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=45)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.productattributes')),
            ],
            options={
                'verbose_name': 'ProductAttributesValues',
                'verbose_name_plural': 'ProductAttributesValues',
            },
        ),
        migrations.CreateModel(
            name='ProductsAsscos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Products_attri_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.productattributes')),
                ('Products_value_attri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.productsasscos')),
            ],
            options={
                'verbose_name': 'ProductsAsscos',
                'verbose_name_plural': 'ProductsAsscos',
            },
        ),
        migrations.CreateModel(
            name='CouponsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('coupons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.coupons')),
            ],
            options={
                'verbose_name': 'CouponsUsed',
                'verbose_name_plural': 'CouponsUsed',
            },
        ),
    ]
