# Generated by Django 3.2 on 2022-08-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_auto_20220824_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.IntegerField()),
                ('AWB_NO', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('grand_total', models.FloatField()),
                ('shipping_charges', models.FloatField()),
                ('billing_address_1', models.CharField(max_length=100)),
                ('billing_address_2', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_country', models.CharField(max_length=100)),
                ('billing_zipcode', models.CharField(max_length=100)),
                ('shipping_address_1', models.CharField(max_length=100)),
                ('shipping_address_2', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_zipcode', models.CharField(max_length=100)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.coupons')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.paymentgateway')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.user')),
            ],
            options={
                'verbose_name': 'UserOrder',
                'verbose_name_plural': 'UserOrder',
            },
        ),
    ]
