# Generated by Django 3.2 on 2022-08-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.products')),
            ],
            options={
                'verbose_name': 'OrderDetails',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
    ]
