# Generated by Django 3.2 on 2022-08-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_admin', '0005_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='auth.group'),
            preserve_default=False,
        ),
    ]
