# Generated by Django 3.2 on 2022-08-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fb_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_token',
        ),
    ]
