# Generated by Django 3.2 on 2022-08-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_auto_20220825_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banners',
            table='custom_admin_banners',
        ),
    ]
