# Generated by Django 3.2 on 2022-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_alter_banners_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='Name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
